services:
  site:
    build: .
    container_name: personal-site
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: yaroslav-fedorov.site
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
